name: Python application

on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master
        
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.7', '3.6', '3.7', '3.8', '3.9' ]
    name: Python ${{ matrix.python-version }} test
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: ". --check"
      - name: Pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install tha package
        run: python setup.py install 
    
